persistence:
  model_store:
    redis_host: localhost
    redis_port: 6379
    redis_db: 1
  lock_store:
    redis_host: localhost
    redis_port: 6379
    redis_db: 2
celery:
  broker: amqp://guest:guest@localhost:5672
  backend: redis://localhost:6379/0
api:
  debug: true
genie_environment:
  template_root_path: example_claims/templates
  pool_size: 1
